src/runtime/translate.ts
test/runtime/translate.test.ts

fix: cannot resolve object path

---

src/directive.ts
src/plugin.ts
test/plugin.test.ts

change to `i18n-t` from `useI18nComponentName`

breaking: rename plugin option name

---

src/index.ts

fix: type exporting

---

src/utils.ts

ref: https://github.com/kazupon/vue-i18n/pull/1020

port: escape ampersand

---

src/errors.ts
src/i18n.ts
test/helper.ts
test/i18n.test.ts

fix: improvement errors

---

examples/composition/scope/inherit-locale.html
examples/legacy/scope/inherit-locale.html
src/i18n.ts
test/i18n.test.ts

fix: useScope inconsistency

---

.github/ISSUE_TEMPLATE.md
README.md

- Fix readme link based on issue #169

Fix readme link

---

examples/composition/formatting/linked.html
examples/legacy/formatting/linked.html
src/core/translate.ts
test/composer.test.ts
test/core/translate.test.ts
test/legacy.test.ts

fix: missing handler not returned

---

src/i18n.ts
src/warnings.ts

fix: improve warning message

---

.textlintrc.js
docs/advanced/composition.md
docs/essentials/started.md
src/composer.ts
src/i18n.ts
src/index.ts
src/mixin.ts
src/vue.d.ts

fix: locale changing for legacy mode

---

packages/vue-i18n/src/composer.ts
packages/vue-i18n/src/index.ts
packages/vue-i18n/test/composer.test.ts
packages/vue-i18n/test/i18n.test.ts
packages/vue-i18n/test/mixin.test.ts

we support i18n custom block fully pre-compilation.
ref: https://github.com/intlify/vue-i18n-loader/pull/146

breaking: change sfc custom block interface

---

packages/message-compiler/src/errors.ts
packages/message-compiler/src/parser.ts
packages/message-compiler/test/__snapshots__/parser.test.ts.snap
packages/message-compiler/test/parser.test.ts

This PR improves parse error messages.

improvement(message-compiler): Improves parse error messages

---

.textlintrc.js
docs/.vitepress/config.js
docs/advanced/optimization.md
docs/installation.md
packages/vue-i18n/package.json

revert: change default ES module bundler module

---

packages/vue-i18n/src/composer.ts
packages/vue-i18n/test/composer.test.ts

fix: fallback root warnings

---

packages/vue-i18n/src/components/base.ts

fix: locale type importing

---

docs/guide/advanced/composition.md

update composition api docs

---

docs/guide/advanced/lazy.md

update lazy loading docs

---

packages/message-compiler/src/transformer.ts

fix: convert Set with Array.from

---

packages/message-compiler/src/tokenizer.ts
packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
packages/message-compiler/test/__snapshots__/parser.test.ts.snap
packages/message-compiler/test/compiler.test.ts
packages/message-compiler/test/parser.test.ts
packages/message-compiler/test/tokenizer/linked.test.ts
packages/message-compiler/test/tokenizer/named.test.ts
spec/syntax.ebnf

fix: cannot use underscore as indentifier

---

jest.config.js
packages/global.d.ts
packages/vue-i18n/README.md
packages/vue-i18n/src/misc.ts
rollup.config.js

resolve
https://github.com/intlify/vue-i18n-next/issues/219#issuecomment-790373841

support suppress esm-bundler feature flags warning

---

examples/lazy-loading/vite/package.json
examples/lazy-loading/vite/yarn.lock
examples/lazy-loading/webpack/package.json
examples/lazy-loading/webpack/yarn.lock

Update some dependencies in example project.
Have tested on `windows 10` and `Ubuntu 20`

Update example project dependencies

---

docs/guide/advanced/component.md

This PR would like to add the pluralization section in component interpolation section.
Relate to #395

docs: add pluralization usage section in component interpolation section

---

package.json
yarn.lock

This reverts commit aeaf18811672385408ef077eee80dccc1afc5c90.

Revert "chore(deps): update dependency typescript to v4.2.3 (#424)"

---

packages/vue-i18n/src/vue.d.ts

https://user-images.githubusercontent.com/3414312/113950543-92a2a080-984c-11eb-918b-643d8d4b627c.png

fix: typing errors

---

docs/.vitepress/theme/index.ts
packages/core-base/src/context.ts
packages/core-base/src/datetime.ts
packages/core-base/src/number.ts
packages/core-base/src/translate.ts
packages/vue-i18n/src/components/formatRenderer.ts
packages/vue-i18n/src/composer.ts
packages/vue-i18n/src/i18n.ts
packages/vue-i18n/src/legacy.ts
packages/vue-i18n/test/helper.ts

ref: https://github.com/intlify/vue-i18n-next/issues/184#issuecomment-818392646

fix: remove object spread literals with object assing

---

package.json
packages/vue-i18n/package.json
packages/vue-i18n/src/devtools.ts
yarn.lock

https://user-images.githubusercontent.com/72989/115946567-128f6280-a4fd-11eb-8732-b6c1292bc627.mov

improvement: target component highlighting on i18n resources inspector

---

packages/core-base/src/context.ts
packages/vue-i18n/src/components/Translation.ts
packages/vue-i18n/src/components/formatRenderer.ts
packages/vue-i18n/src/i18n.ts

Minor improvements for some condition judgment to make them more clear.

Simplify some condition judgments

---

docs/guide/essentials/syntax.md

Fix syntax error in quote example.

---

docs/guide/essentials/pluralization.md
docs/guide/essentials/syntax.md
docs/introduction.md

I found a few typos in the docs.
I hope this will help.

docs: fix typo

---

examples/lazy-loading/vite/src/i18n.ts

fix: lazy-loading example

---

package.json
yarn.lock

Reverts intlify/vue-i18n-next#511

Revert "chore(deps): update dependency typescript to v4.3.2"

---

package.json
packages/vue-i18n/test/i18n.test.ts

Node v10 have been already EOL
https://nodejs.org/en/about/releases/

drop node v10

---

packages/core-base/src/index.ts

fix: __INTLIFY_PROD_DEVTOOLS__ is not defined

---

docs/guide/essentials/number.md

Fix VueJS Syntax

---

packages/core-base/src/index.ts

fix: __INTLIFY_PROD_DEVTOOLS__ is not defined (#532)

---

packages/vue-i18n-core/src/devtools.ts

fix null access of __VUE_I18n__

---

docs/guide/advanced/typescript.md

docs: typo in typescript.md

---

package.json
yarn.lock

Reverts intlify/vue-i18n-next#625

Revert "chore(deps): update dependency vitepress to ^0.16.0"

---

docs/guide/migration/breaking.md
docs/ja/guide/migration/breaking.md

ref: https://github.com/intlify/vue-i18n-next/issues/220#issuecomment-904563333

docs: update breaking changes section

---

docs/api/injection.md

docs: add support api mode for injection APIs

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/utils.ts

fix: __INTLIFY_META__ access error in vue-i18n-bridge

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/utils.ts

fix: createI18n second argument type error

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/utils.ts

fix: custom block reosurce processing errors

---

docs/guide/migration/ways.md
jest.config.js
packages/vue-i18n-bridge/README.md
packages/vue-i18n-bridge/src/index.ts
packages/vue-i18n-bridge/src/runtime.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/index.ts
packages/vue-i18n-core/test/i18n.test.ts

improvement: expose type casting API for Legacy mode

---

packages/vue-i18n-core/src/mixins/bridge.ts

ref: https://github.com/intlify/bundle-tools/tree/main/packages/vue-i18n-loader#bridge

improvement: support vue-i18n-loader bridge mode

---

packages/vue-i18n-core/src/components/DatetimeFormat.ts
packages/vue-i18n-core/src/components/NumberFormat.ts
packages/vue-i18n-core/src/components/Translation.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/mixins/next.ts
packages/vue-i18n-core/src/symbols.ts
packages/vue-i18n-core/test/components/Translation.test.ts

fix: vue-i18n components scope resolving in Legacy API mode

---

docs/guide/advanced/optimization.md
docs/guide/advanced/sfc.md
docs/ja/guide/advanced/optimization.md
docs/ja/guide/advanced/sfc.md

feat(docs): add usage with Quasar CLI

---

docs/guide/essentials/fallback.md

docs: improve doc of fall back warinings

---

docs/guide/migration/ways.md
package.json
packages/vue-i18n-core/src/i18n.ts
scripts/build.sh
scripts/postprocess.ts

fix: typescript errors with vue-tsc on vue-i18n-bridge

---

packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/mixins/next.ts
packages/vue-i18n-core/src/utils.ts
packages/vue-i18n-core/test/i18n.test.ts

fix: merge global resources of i18n custom block

---

packages/vue-i18n-core/src/components/utils.ts
packages/vue-i18n-core/test/components/Translation.test.ts

fix: cannot work correctly v-for on Translation component

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/issues.test.ts

fix: inherit warn html message setting option

---

packages/vue-i18n-core/src/mixins/next.ts

fix: null access on mount hook

---

test-d/vue-i18n/i18n.test-d.ts

fix: revert type test case change in strictI18n

fix: revert type test case change in strictI18n

---

package.json
pnpm-lock.yaml

Reverts intlify/vue-i18n-next#927

Revert "chore(deps): update dependency vitepress to ^0.22.0"

---

packages/core-base/src/context.ts
packages/core-base/src/runtime.ts
packages/core-base/src/translate.ts
packages/core-base/test/translate.test.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/issues.test.ts

fix: linked message fallbacking

---

packages/vue-i18n-core/src/errors.ts
packages/vue-i18n-core/src/i18n.ts

fix: nullish assignment

---

packages/core-base/src/translate.ts
packages/vue-i18n-core/test/issues.test.ts

fix: resolve default message value

---

packages/vue-i18n-core/src/components/formatRenderer.ts
packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
packages/vue-i18n-core/test/issues.test.ts

fix(components): strictly slot rendering

---

docs/guide/migration/vue3.md

docs: Update vue3.md

---

packages/core-base/src/datetime.ts
packages/core-base/src/number.ts
packages/core-base/test/datetime.test.ts
packages/core-base/test/number.test.ts
packages/vue-i18n-core/test/composer.test.ts

fix: number & datetime format options

---

packages/core-base/src/context.ts
packages/core-base/src/translate.ts
packages/core-base/test/translate.test.ts
packages/vue-i18n-core/test/composer.test.ts

fix postTranslation option

---

scripts/build.ts

1. fix that `isExist` always returns false no matter if the file exists
2. fix `await` that has no effect in line 205: `await !isExist(filePath)` => `!(await isExist(filePath))`
3. polish code and try to add some types btw
Thanks!

fix: fix isExist always returns false and polish build.ts

---

docs/guide/essentials/syntax.md
packages/message-compiler/src/generator.ts
packages/vue-i18n-core/src/composer.ts

Thanks for making this great project!
This pr fixes some typos I found while reading the source code and makes a small code refactoring.

fix typo and polish

---

packages/message-compiler/src/tokenizer.ts
packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
packages/message-compiler/test/compiler.test.ts
packages/message-compiler/test/parser/__snapshots__/modulo.test.ts.snap
packages/message-compiler/test/parser/modulo.test.ts
packages/message-compiler/test/tokenizer/__snapshots__/named.test.ts.snap
packages/message-compiler/test/tokenizer/named.test.ts
packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
packages/vue-i18n-core/test/issues.test.ts

fix: cannot modulo parse hangup

---

examples/bridge/composition/scope/local.html
packages/vue-i18n-core/src/i18n.ts

fix: lifecycle hook context binding

---

examples/ssr/vite/src/main.js
packages/vue-i18n-core/src/directive.ts
packages/vue-i18n-core/test/issues.test.ts

fix: v-t directive reactivity

---

docs/guide/essentials/scope.md

i18n.global.locale is a ref - so the example should be assigning to it in the correct manner

i18n.global.locale is a ref

---

packages/vue-i18n-core/src/components/utils.ts
packages/vue-i18n-core/test/issues.test.ts

fix:using the better Fragment detection(#1122)

---

docs/.ja/api/general.md
packages/vue-i18n-core/src/i18n.ts

Fix typo in createI18n

---

docs/guide/index.md

docs: update introduction

---

packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/mixins/bridge.ts
packages/vue-i18n-core/src/mixins/next.ts
packages/vue-i18n-core/test/helper.ts
packages/vue-i18n-core/test/i18n.test.ts

This is a fix PR for https://github.com/nuxt-community/i18n-module/issues/1659
So, plugin options are internally and undocumented feature

fix: exntending for Composer and VueI18n

---

packages/vue-i18n-core/src/mixins/next.ts
packages/vue-i18n-core/test/i18n.test.ts

related https://github.com/nuxt-community/i18n-module/issues/1659

fix: multiple VueI18n extending

---

docs/.ja/guide/advanced/component.md
docs/.ja/guide/migration/breaking.md
docs/guide/advanced/component.md
docs/guide/integrations/nuxt3.md
docs/guide/migration/breaking.md
examples/frameworks/nuxt3/README.md
examples/frameworks/nuxt3/nuxt.config.ts
examples/frameworks/nuxt3/tsconfig.json

Update all nuxt-3 links
Update some vue-3 migration guide links

docs: update links

---

scripts/release.sh

fix: generate ComponentCustomProperties d.ts

---

packages/core-base/src/context.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/legacy.ts
pnpm-lock.yaml
test-d/core-base/runtime.test-d.ts
test-d/vue-i18n/i18n.test-d.ts

fix: useI18n wrong type and other type broken

---

packages/vue-i18n-bridge/src/vue.d.ts
packages/vue-i18n/src/vue.d.ts

fix: support pascal case for components

---

docs/guide/roadmap.md

Hello, this is a small change that fixes kanban typo.
Have a nice day :)

Fix: kanban misspell

---

docs/guide/advanced/typescript.md

Add some details about typing properly `createI18n()` with type hints for `Legacy` and `Options` type parameters

Improve documentation about TypeScript Support

---

docs/guide/integrations/nuxt3.md

I created a simple project following this integration guide and added [a custom github action that could translate locale jsons using deepL](https://github.com/lyqht/deepl-translate-github-action/). 
I thought that this will be a good example code project to be added into the integration guide.

Add example code for deployed app for nuxt3-app-vue-i18n

---

packages/vue-i18n-core/src/composer.ts

fix: root context message availability for linked messages in SFCs on production

---

docs/guide/advanced/optimization.md

Fix [vite-plugin-vue-i18n - Configure](https://vue-i18n.intlify.dev/guide/advanced/optimization.html#configure-plugin-for-vite) and [unplugin-vue-i18n - Configure plugin for webpack](https://vue-i18n.intlify.dev/guide/advanced/optimization.html#configure-plugin-for-webpack) typo.

fix(guide): typo resourece -> resource

---

docs/guide/integrations/nuxt3.md

docs: diff with syntax highlighting in nuxt integration

---

packages/petite-vue-i18n/src/index.ts
packages/petite-vue-i18n/src/runtime.ts
packages/vue-i18n-bridge/src/index.ts
packages/vue-i18n-bridge/src/runtime.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/index.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/mixins/next.ts
packages/vue-i18n-core/src/symbols.ts
packages/vue-i18n-core/src/types.ts
packages/vue-i18n-core/test/i18n.test.ts
packages/vue-i18n/src/index.ts
packages/vue-i18n/src/runtime.ts

releated https://github.com/nuxt-modules/i18n/issues/2315

fix: improve custom extender

---

packages/vue-i18n-core/src/directive.ts
packages/vue-i18n-core/src/index.ts
packages/vue-i18n/src/index.ts
packages/vue-i18n/src/runtime.ts

feat: export `v-t` directive type

---

packages/vue-i18n-bridge/package.json
pnpm-lock.yaml

fix(vue-i18n-bridge): peer dependency warning

---

scripts/release.sh

chore: fix release with latest tag

---

docs/guide/integrations/nuxt3.md

docs: add build.transpile option

---

docs/guide/integrations/nuxt3.md
packages/message-compiler/src/tokenizer.ts
packages/message-compiler/test/tokenizer/linked.test.ts
packages/vue-i18n-core/test/issues.test.ts

fix: cannot resolve linked refer message

---

packages/vue-i18n-core/test/issues.test.ts

resolve #1538
(this issue was already fixed by #1549)

fix: cannot resolve linked refer message that has hypen

---

packages/core-base/src/context.ts
packages/core-base/src/devtools.ts
packages/core-base/src/runtime.ts

fix: type errors for core-base

---

examples/frameworks/nuxt3/nuxt.config.ts

Add build.transpile to Nuxt config.
Solution  to address the problem documented in the GitHub issue at https://github.com/nuxt/nuxt/issues/23180.

Update nuxt.config.ts in Nuxt 3 Minimal Starter Example

---

packages/core-base/src/format.ts
packages/core-base/test/compilation.test.ts

ref: https://github.com/nuxt-modules/i18n/issues/2437

fix(core-base): wrong list index resolving on jit optimization

---

examples/lazy-loading/vite/src/i18n.ts

resolve #1575 
ref: https://github.com/vitejs/vite/pull/14006

fix(examples): remove `@vite-ignore` magic comment

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/issues.test.ts

fix: cannot resolve flatjson messages when use `setLocaleMessage`

---

netlify.toml
package.json
renovate.json

fix: revert pnpm

---

packages/core-base/src/translate.ts

fix: wrong source getting

---

packages/core/package.json

ref: https://github.com/nuxt-modules/i18n/pull/2558
Nitro (rollup) does not resolve correctly

fix: tweak `@intlify/core` conditional exports

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/issues.test.ts

resolves #1717
more info in issue

fix: key-value style messages broken after merging (#1717)

---

docs/api/injection.md

Fix typo in `injection.md` file.

chore(typo): update injection.md

---

docs/guide/advanced/sfc.md

If they live somewhere else, please inform me and I will update this PR.

refactor(broken-links): Remove broken links in sfc.md

---

packages/vue-i18n-core/src/i18n.ts

Reverts intlify/vue-i18n-next#1631

Revert "chore(fix): #1630 make the install function synchronous to be aligned…"

---

renovate.json

related nuxt-modules/i18n#2827
The following this changes were made in this PR.
- `config:base` is renamed to `config:recommended`.
- ref: [renovatebot/renovate#21136](https://github.com/renovatebot/renovate/pull/21136)

chore: update extends in renovate

---

docs/.vitepress/config.mts

docs: fix dead link on menu

---

packages/core/package.json
packages/core/src/index.ts
packages/petite-vue-i18n/package.json
packages/vue-i18n/package.json
rollup.config.mjs

fix: Not load devtools on Node.js

---

packages/core-base/src/runtime.ts
packages/core-base/src/translate.ts
packages/core-base/test/translate.test.ts
packages/vue-i18n-core/test/issues.test.ts

fix: fallback linked message params

---

package.json
packages/format-explorer/vite.config.ts
pnpm-lock.yaml
scripts/build.ts
scripts/dev.ts

chore(deps): update `execa` to v9

---

packages/shared/src/utils.ts

Reasoning described https://github.com/intlify/vue-i18n/pull/1947#issuecomment-2349404788, might have slight performance improvement since it's used often, but it's a small change.

fix: revert #1379

---

docs/guide/essentials/pluralization.md

- edited this page to improve readablity

docs: Pluralization Page

---

packages/core-base/src/runtime.ts

Sorry, didn't see that one when I did #2040

Fix another typo

---

packages/vue-i18n-core/src/directive.ts

fix: v-t custom directive warning when it will run

---

docs/guide/installation.md

The commands are not updated with the new version.

fix(installation.md): update installation commands for package manager

---

packages/core-base/package.json
packages/core/package.json
packages/devtools-types/package.json
packages/message-compiler/package.json
packages/petite-vue-i18n/package.json
packages/shared/package.json
packages/vue-i18n-core/package.json
packages/vue-i18n/package.json

fix: ESM only with package.json type field

---

packages/core-base/src/ast.ts
packages/core-base/src/compilation.ts
packages/core-base/src/format.ts
packages/core-base/src/index.ts
packages/core-base/src/resolver.ts
packages/core-base/src/translate.ts
packages/core-base/test/compilation.test.ts
packages/core-base/test/fixtures/ast.ts
packages/core-base/test/resolver.test.ts
packages/core-base/test/translate.test.ts
packages/vue-i18n-core/src/utils.ts
packages/vue-i18n-core/test/fixtures/ast.ts
packages/vue-i18n-core/test/issues.test.ts
packages/vue-i18n-core/test/utils.test.ts

fix: cannot resolve the ast messages which has json path for v10

---

packages/vue-i18n-core/src/components/Translation.ts

We will add another internal key `__`, see https://github.com/vuejs/core/pull/13215/files

fix: update slot key filtering to exclude internal keys

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test-d.ts
packages/vue-i18n/src/vue.d.ts

fix: n() & d() output depending "part" option
