examples/composable/fallback/basic.html
examples/composable/fallback/default-format.html
examples/composable/fallback/option.html
examples/composable/fallback/suppress.html
examples/composable/missing/handler.html
examples/composable/missing/option.html
examples/composable/missing/suppress.html
src/composer.ts
src/legacy.ts
src/runtime/context.ts
src/runtime/datetime.ts
src/runtime/number.ts
src/runtime/translate.ts
test/composer.test.ts
test/runtime/context.test.ts
test/runtime/datetime.test.ts
test/runtime/number.test.ts
test/runtime/translate.test.ts

- automatic implicit fallback on locales with territory and dialects
- without explicit fallback (`false`)
- array of fallback locales
- decision map with fallbacks as described
related: https://github.com/kazupon/vue-i18n/pull/829
- remove `fallbackLocales` property of comoposr

enhancement locale fallbacking

---

.github/CONTRIBUTING.md
README.md

Just a handful of minor corrections to the README and the CONTRIBUTING markdown files.

Minor typo fixes

---

README.md
src/composer.ts
src/legacy.ts
src/message/compiler.ts
src/message/options.ts
src/runtime/context.ts
src/runtime/translate.ts
test/legacy.test.ts
test/message/__snapshots__/compiler.test.ts.snap
test/message/compiler.test.ts
test/runtime/translate.test.ts

- Composable API: `warnHtmlMessage` boolean option, default `true`.
- For development mode, warning is default.
- For production mode, HTML message detect is not check due to performance.

breaking: HTML message warning

---

package.json
src/composer.ts
src/core/context.ts
src/core/translate.ts
src/index.ts
src/message/compiler.ts
src/message/runtime.ts
src/utils.ts
test/message/compiler.test.ts
yarn.lock

vue-i18n-next can  support precompile with vue-i18n-loader, as result improve performance

feat: support pre-compile locale messages

---

README.md
e2e/fallback/component.test.js
e2e/scope/inherit-locale.test.js
e2e/scope/local.test.js
examples/composable/scope/inherit-locale.html
examples/legacy/scope/inherit-locale.html
src/components/DatetimeFormat.ts
src/components/NumberFormat.ts
src/components/Translation.ts
src/composer.ts
src/i18n.ts
src/index.ts
src/legacy.ts
src/mixin.ts
src/plugin.ts
test/composer.test.ts
test/i18n.test.ts

- Legacy API `sync` option:
- default: change to `false` from `true`

Breaking: inherit locale

---

.github/workflows/test.yml
README.md
e2e/directive/basic.test.js
e2e/directive/object.test.js
e2e/directive/plural.test.js
e2e/directive/preserve.test.js
e2e/helper.js
examples/composable/directive/basic.html
examples/composable/directive/object.html
examples/composable/directive/plural.html
examples/composable/directive/preserve.html
examples/legacy/directive/basic.html
examples/legacy/directive/object.html
examples/legacy/directive/plural.html
examples/legacy/directive/preserve.html
package.json
src/directive.ts
src/legacy.ts
src/plugin.ts
yarn.lock

- `v-t` directive
- `preserve` modifier deprecated, keep Element content
- Legacy API `preserveDirectiveContent` option, and property deprecated

breaking: v-t directive

---

README.md
src/legacy.ts
src/mixin.ts
test/legacy.test.ts
test/mixin.test.ts

compatible for legacy API
ref:
https://github.com/kazupon/vue-i18n/pull/892

feat: componentInstanceCreatedListener option

---

src/message/parser.ts
src/message/tokenizer.ts
test/message/__snapshots__/compiler.test.ts.snap
test/message/__snapshots__/tokenizer.test.ts.snap
test/message/compiler.test.ts
test/message/parser/__snapshots__/modulo.test.ts.snap
test/message/parser/modulo.test.ts
test/message/tokenizer/linked.test.ts
test/message/tokenizer/named.test.ts
test/message/tokenizer/plural.test.ts
test/message/tokenizer/text.test.ts

fix modulo case

---

src/composer.ts

remove computed wrapping

---

src/components/Translation.ts
src/components/base.ts
src/components/formatRenderer.ts
test/components/DatetimeFormat.test.ts
test/components/NumberFormat.test.ts
test/components/Translation.test.ts

refs:
- https://github.com/kazupon/vue-i18n/pull/928
- https://github.com/kazupon/vue-i18n/pull/959

port i18n or i18n-d component tag props

---

package.json
src/directive.ts
test/diretive.test.ts
test/ssr.test.ts
yarn.lock

Most features of vue-i18n-next are supported SSR by Vue.
`v-t` SSR can be supported by `vue-i18n-exntensions` and Vue compiler.
https://github.com/intlify/vue-i18n-extensions/releases/tag/v2.0.0-alpha.2

support server-side rendering 

---

README.md
src/composer.ts
src/legacy.ts
src/mixin.ts
test/composer.test.ts
test/legacy.test.ts

resolve #75 
add the bellow API:
- Composable API style
- Composer: tm method
- Legacy API style
- VueI18n: tm method
- Injection of Vue prototype: $tm

feat: how to get locale messages from a given key

---

src/i18n.ts

- When `emptyOption` is `true`, `scope` is always `global`
- When `scope` is `global`, we do not need to call `getCurrentInstance`, so it's better to return earlier than `getCurrentInstance()`
---
BTW, the following snippet might not be necessary:
```ts
if (instance == null) {
throw createI18nError(I18nErrorCodes.UNEXPECTED_ERROR)
}
```
Becasue if the currentInstance is not available, the `inject()` api will return `undefined` and an error has already been thrown:
```ts
const i18n = inject(I18nSymbol) as I18n<
Messages,
DateTimeFormats,
NumberFormats
>
if (!i18n) {
throw createI18nError(I18nErrorCodes.NOT_INSLALLED)
}
```

refactor: simplify scope cases

---

rollup.config.js

This global var doesn't match it's definition (due to missing `I`) which causes the entire vite (esm) production build to fail with:
```
ReferenceError: __INTLFY_PROD_DEVTOOLS__ is not defined
``` 
fallback defined in `mist.ts`:
``` 
if (typeof __FEATURE_PROD_DEVTOOLS__ !== 'boolean') {
needWarn = true
getGlobalThis().__INTLIFY_PROD_DEVTOOLS__ = false
}
```

Fix devtools typo

---

src/composer.ts
test/composer.test.ts

port: https://github.com/kazupon/vue-i18n/pull/995

fix: merge custom block locale messages

---

examples/composable/scope/global.html
examples/composable/scope/inherit-locale.html
examples/composable/scope/local.html
examples/composable/started.html
package.json
src/directive.ts
src/errors.ts
src/i18n.ts
src/index.ts
src/vue.d.ts
test/diretive.test.ts
test/mixin.test.ts

resolve #106
This PR is a PR to improve the DX of the API vue-i18n-next provides for the composition API.
This PR improves the following:
- no longer needs to call `useI18n` on each component when using global composer
- The following global props & methods are injected by `app.config.globalProperties`
- `$i18n` prop: exported `locale`, `fallbackLocale` and `availableLocales` props
- `$t` method
- `$d` method
- `$n` method
- `$tm` method

feat: global props and methods injection for composable mode

---

src/errors.ts

During my tests I found a typo in one of the error messages, as demonstrated below:

Fix `UNEXPECTED_ERROR` message typo

---

README.md
src/composer.ts
src/core/context.ts
src/core/translate.ts
src/legacy.ts
src/utils.ts
test/core/context.test.ts
test/core/translate.test.ts

port https://github.com/kazupon/vue-i18n/issues/1002

feat: escape html parameter options

---

README.md
devtools-test/yarn.lock
format-explorer/package.json
format-explorer/src/App.vue
format-explorer/src/components/Editor.vue
format-explorer/src/components/Navigation.vue
format-explorer/src/index.css
format-explorer/src/utils.ts
format-explorer/webpack.config.js
format-explorer/yarn.lock
package.json
rollup.config.js
src/message/compiler.ts
src/message/generator.ts
src/message/location.ts
src/message/options.ts
src/message/parser.ts
test/message/__snapshots__/generator.test.ts.snap
test/message/__snapshots__/parser.test.ts.snap
test/message/__snapshots__/transformer.test.ts.snap
test/message/generator.test.ts
test/message/parser/__snapshots__/linked.test.ts.snap
test/message/parser/__snapshots__/list.test.ts.snap
test/message/parser/__snapshots__/literal.test.ts.snap
test/message/parser/__snapshots__/modulo.test.ts.snap
test/message/parser/__snapshots__/named.test.ts.snap
test/message/parser/__snapshots__/plural.test.ts.snap
test/message/parser/__snapshots__/text.test.ts.snap
yarn.lock

feat: support source map for message functions

---

src/composer.ts
src/core/datetime.ts
src/core/errors.ts
test/composer.test.ts
test/core/datetime.test.ts

Currently, only Date objects and number are allowed.
While using number may cause many problems (missing timezone information), a ISO string is a format returned by most APIs. So in my opinion, it makes more sense to allow an (ISO) string to be passed to this method.

Allow d() to take an ISO string as parameter.

---

src/composer.ts

`translateVNode` crashes in `finally` clause because `_context` variable doesn't exist in scope

fix: can't assign to property "processor" on false: not an object

---

docs/advanced/optimization.md
docs/api/injection.md
docs/installation.md
packages/vue-i18n/src/composer.ts
packages/vue-i18n/src/vue.d.ts

Fixes found typos while reading docs

docs: fix various typos

---

packages/message-compiler/src/parser.ts
packages/message-compiler/src/tokenizer.ts

This PR fixes an issue where passing `true` to `ParserOptions.location` would cause the parser not to generate the `loc`.

Fix not to get loc when passing true to ParserOptions.location

---

packages/message-compiler/src/parser.ts
packages/message-compiler/test/__snapshots__/parser.test.ts.snap
packages/message-compiler/test/parser.test.ts

This PR improves AST and error emission when the linked message is misformatted.
e.g.
- `@:(foo)`:
- before:  
```js
body: [
{
type: /* LinkedNode */
}
],
errors: []
```
- after:  
```js
body: [
{
type: /* LinkedNode */,
key: {
type: /* LinkedKeyNode */,
value: '' /*empty*/
}
},
{
type: /* TextNode */,
value: '(foo)'
}
],
errors: [
{ message: "Unexpected lexical analysis in token: 'xx'"}
]
```
- `@.:foo`:
- before:  
```js
body: [
{
type: /* LinkedNode */,
modifier: {
value: ':'
}
}
],
errors: [
{ message: "Unexpected lexical analysis in token: 'xx'"}
]
```
- after:  
```js
body: [
{
type: /* LinkedNode */,
modifier: {
value: ''  /*empty*/
},
key: {
type: /* LinkedKeyNode */,
value: 'foo'
}
},
],
errors: [
{ message: "Unexpected lexical analysis in token: 'xx'"}
]
```
- `@.: foo`:
- …

improvement(message-compiler): Change to generate AST with linked message error

---

docs/installation.md

Adding an example showing how to `import` from a different build.  This is the one asked about most frequently on Stack Overflow, so I think it's nice to have in this section, but maybe it should go somewhere else.

docs: update installing for esm bundler

---

packages/vue-i18n/test/composer.test.ts

The test 'minimumFractionDigits, maximumFractionDigits' failed with log
```
● n › minimumFractionDigits, maximumFractionDigits
expect(received).toEqual(expected) // deep equality
Expected: "$0.99"
Received: "US$ 0.99"
746 |       }
747 |     })
> 748 |     expect(n(0.99, { key: 'currency', fallbackWarn: false })).toEqual('$0.99')
|                                                               ^
749 |     expect(n(1.1111, { key: 'decimal', fallbackWarn: false })).toEqual('1.11')
750 |   })
751 | 
at Object.<anonymous> (packages/vue-i18n/test/composer.test.ts:748:63)
```
This problem is caused by the `Intl.NumberFormat` : we are testing with locale `US`, which is not supported locale
```javascript
const locales1 = ['US', 'en-US'];
const options1 = { localeMatcher: 'lookup' }; …
```

fix #262: test fail in some cases

---

examples/lazy-loading/webpack/src/App.vue
examples/lazy-loading/webpack/src/i18n.js
examples/lazy-loading/webpack/src/router.js
examples/lazy-loading/webpack/webpack.config.js

This is a fix for #259, including:
1. return 404 when user directly access page or refresh page if current page's path is not '/'
2. jump to default home page when directly access a specific language page
3. jump to default home page in some case when switch the language label
And do also:
1. redirect to default home page when access a specific language page that does not exit

Fix #259 : fix some problems of example prtoject lazy-loading/webpack

---

packages/message-resolver/src/index.ts
packages/message-resolver/test/index.test.ts
packages/vue-i18n/src/composer.ts
packages/vue-i18n/test/i18n.test.ts

This is an implemention for #271.
With `handleFlatJson`, we can recrusively search the object for keys containing dot('.'), and transform the flat structure to normal structure so we can handle them as before.
The corresponding tests are also included.

Add support for flat json separated with dot('.')

---

docs/guide/advanced/sfc.md

I think it was "messages" unless my English is failing me. My bad if it is the case. Thanks for your work btw !

Fix spelling line 195 for sfc doc : lessages to messages

---

packages/vue-i18n/test/i18n.test.ts

Simplify some tests: 
1.replace `===` with `toEqual`
2.replace `!==` with `not.toEqual`
This makes statement shorter and more precise.

simplify some tests

---

packages/core-base/src/context.ts
packages/core-base/test/context.test.ts

Fix #328
Fix won't fallback when `fallbackLocale` is empty string, and add a test.

fix won't fallback when `fallbackLocale` is empty string, and add a test

---

package.json
packages/vue-i18n/package.json
packages/vue-i18n/src/devtools.ts
yarn.lock

fix: support vue-devtools component inspector custom tags breaking change

---

packages/vue-i18n/src/composer.ts
packages/vue-i18n/test/composer.test.ts
packages/vue-i18n/test/i18n.test.ts
packages/vue-i18n/test/legacy.test.ts

The existing `mergeLocaleMessage` use `Object.assign` to merge. 
There is some problems when merge two complex object.
These problems could be tested with my testcase which I have modified in this PR.
This PR would like to fix these problems.

fix for function `mergeLocaleMessage`, and modify some tests

---

packages/vue-i18n/src/i18n.ts

Fix for `globalInjection` not being enabled when `__VUE_I18N_LEGACY_API__` is set to `false

fix: feature flags

---

.gitignore

Sometimes `vscode` will create a `debug.log` file, maybe we can ignore it.

Ignore debug.log file that create by vscode

---

examples/lazy-loading/vite/package.json
examples/lazy-loading/vite/src/i18n.ts
examples/lazy-loading/vite/yarn.lock

The official version of vite 2.0.0 has been released. 
I think we can update the vite version of the example project to the latest version (2.0.2).
I've just tested it on my machine, we just need a little change to the `i18n. ts` file, then everything works fine.

update example project vite version to ^2.0.2

---

examples/lazy-loading/vite/src/App.vue
examples/lazy-loading/webpack/src/App.vue

There is a warning in example project `examples/lazy-loading/webpack` and `examples/lazy-loading/vite` :
```
[vue/valid-template-root]
The template root requires exactly one element.eslint-plugin-vue
```
This PR is a fix for it.

Fix eslint warning in example project

---

packages/message-compiler/src/compiler.ts
packages/message-compiler/src/parser.ts
packages/shared/src/index.ts
packages/vue-i18n/src/components/DatetimeFormat.ts
packages/vue-i18n/src/components/NumberFormat.ts
packages/vue-i18n/src/components/Translation.ts
packages/vue-i18n/src/components/formatRenderer.ts

fix: Support for browsers that don't support object spread literals

---

docs/api/injection.md
packages/vue-i18n/src/composer.ts
packages/vue-i18n/src/legacy.ts
packages/vue-i18n/src/vue.d.ts
packages/vue-i18n/test/composer.test.ts
packages/vue-i18n/test/legacy.test.ts

fix: cannot fallback at tm / $tm

---

docs/ecosystem/third.md

Refers to issue #400. Added short description about my plugin.

Add easy-i18n as third-party tool

---

docs/api/injection.md
docs/guide/advanced/composition.md
packages/core-base/src/translate.ts
packages/core-base/test/translate.test.ts
packages/vue-i18n/src/composer.ts
packages/vue-i18n/src/i18n.ts
packages/vue-i18n/src/legacy.ts
packages/vue-i18n/src/mixin.ts
packages/vue-i18n/src/vue.d.ts
packages/vue-i18n/test/composer.test.ts
packages/vue-i18n/test/legacy.test.ts
packages/vue-i18n/test/mixin.test.ts
renovate.json

feat: resolve locale message translation new API `rt`

---

packages/core-base/src/types.ts

Hi, this PR aims to solve a build issue that occurs when you use vue-i18n 9.0.0 with Vite & Vue 3
Here is the error:
```
vue-tsc --noEmit && vite build
node_modules/@intlify/core-base/dist/core-base.d.ts:526:26 - error TS2430: Interface 'SpecificDateTimeFormatOptions' incorrectly extends interface 'DateTimeFormatOptions'.
Types of property 'localeMatcher' are incompatible.
Type '"lookup" | "best-fit" | undefined' is not assignable to type '"best fit" | "lookup" | undefined'.
Type '"best-fit"' is not assignable to type '"best fit" | "lookup" | undefined'.
526 export declare interface SpecificDateTimeFormatOptions extends Intl.DateTimeFormatOptions {
```
On vue-i18n, best-fit was renamed to best-fit in 8.X but the change has not been propagated to core-base
Here is the original PR: …

Coherent update from 'best-fit' to 'best fit'

---

examples/lazy-loading/vite/src/router.ts
examples/lazy-loading/webpack/src/router.js

Modify navigation guards:
1. Remove parameter `from` because it's not used
2. Remove parameter `next`， use recommended way by `vue router ` for instead, see also [this](https://next.router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards)

Modify some router setups in example projects

---

docs/guide/advanced/optimization.md
packages/core-base/src/context.ts
packages/core-base/src/translate.ts
packages/global.d.ts
packages/size-check-vue-i18n/rollup.config.js
packages/vue-i18n/README.md
packages/vue-i18n/src/devtools.ts
packages/vue-i18n/src/i18n.ts
packages/vue-i18n/src/index.ts
packages/vue-i18n/src/misc.ts
packages/vue-i18n/src/mixin.ts
packages/vue-i18n/src/runtime.ts
rollup.config.js

To provide experimental features for `@intlify/devtools`, feature flags have been separated as follows.
- `__VUE_I18N_PROD_DEVTOOLS__`: enable/disable vue-devtools support in production, default: false
- `__INTLIFY_PROD_DEVTOOLS__`: enable/disable `@intlify/devtools` support in production, default: false
Previously, `__INTLIFY_PROD_DEVTOOLS__` setting flagged the use of both vue-devtools and `@intlify/devtools` in production.
In later v9.1, The feature flags for vue-devtools are now enabled/disabled by setting `__VUE_I18N_PROD_DEVTOOLS__`.

breaking: split devtools production feature flags

---

packages/vue-i18n/src/components/DatetimeFormat.ts
packages/vue-i18n/src/components/NumberFormat.ts
packages/vue-i18n/src/components/Translation.ts
packages/vue-i18n/src/components/base.ts

When using `<i18n-t>` inside a slot of a custom component, it will try to use the scope of the parent component, but because of being inserted into a slot, its parent is now that custom component instead of the original parent component, where the template that used `<i18n-t>` was compiled. As a more concrete example:
1. `Parent` component defines an i18n scope, and a message with key `hello`.
2. `Parent` component uses `Child` component in its template.
3. `Child` component defines a slot named `content` and a new i18n scope (without any messages).
4. `Parent` component uses `<i18n-t keypath="hello">` inside the `content` slot of `Child` component.
5. `<i18n-t>` looks for the message with key `hello` but can't find it in its "parent" component because it's not longer `Parent`, but …

Support passing composer instance to Translation component

---

packages/vue-i18n/src/components/base.ts

fix vue-i18n type definition broken

---

docs/guide/essentials/number.md
packages/vue-i18n/test/composer.test.ts

Some users may not be familiar with `numberFormats`. See #481
This PR consists of some tests about `minimumSignificantDigits, maximumSignificantDigits` and `notation`. I'm trying to show some examples about the usage of these configurations. Hoping this can make it more clear.

Add some tests about numberFormats

---

jest.config.js
packages/global.d.ts
packages/vue-i18n/README.md
packages/vue-i18n/src/misc.ts
rollup.config.js

The `__FEATURE_ESM_BUNDLER_WARN__` is replaced to be `true` in `rollup.config.js`, which make it being impossible to be configured.
Fix #461

Fix __FEATURE_ESM_BUNDLER_WARN__ flag can not be configured

---

packages/vue-i18n/src/mixin.ts
packages/vue-i18n/test/i18n.test.ts

fix: cannot hook at beforeUnmount/unmounted

---

docs/api/injection.md
docs/ja/api/injection.md
packages/vue-i18n/src/vue.d.ts

Fix typing to match usage in examples https://github.com/intlify/vue-i18n-next/blob/master/docs/guide/essentials/number.md
```html
<p>{{ $n(10000, 'currency') }}</p>
<p>{{ $n(10000, 'currency', 'ja-JP') }}</p>
<p>{{ $n(10000, 'currency', 'ja-JP', { useGrouping: false }) }}</p>
<p>{{ $n(987654321, 'currency', { notation: 'compact' }) }}</p>
<p>{{ $n(0.99123, 'percent') }}</p>
<p>{{ $n(0.99123, 'percent', { minimumFractionDigits: 2 }) }}</p>
<p>{{ $n(12.11612345, 'decimal') }}</p>
<p>{{ $n(12145281111, 'decimal', 'ja-JP') }}</p>
```
Linked issue: https://github.com/intlify/vue-i18n-next/issues/540

Add number formatting missing type definition

---

examples/lazy-loading/vite/package.json
examples/lazy-loading/vite/yarn.lock
examples/tsx/yarn.lock
examples/type-safe/global-type-definition/package.json
examples/type-safe/global-type-definition/yarn.lock
examples/type-safe/type-annotation/package.json
examples/type-safe/type-annotation/yarn.lock
packages/vue-i18n/src/vue.d.ts

In some example projects, It seems that the relative path of vue-i18n is wrong.
For example, in `examples/lazy-loading/vite/package.json`, Now the configuration is :
```
"vue-i18n": "link:../../packages/vue-i18n"
```
But the correct relative path would be
```
"vue-i18n": "link:../../../packages/vue-i18n"
``` 
This PR fix these wrong conifgs, and update some yarn.lock files.

fix: wrong vue-i18n path config in some example projects

---

docs/api/injection.md
docs/ja/api/injection.md
packages/vue-i18n/src/legacy.ts
packages/vue-i18n/src/vue.d.ts

Allow use of boolean and numbers in args to handle args such as:
- useGrouping
- maximumFractionDigits
- minimumFractionDigits
- ....

Allow number and boolean in args of number formatting

---

docs/guide/advanced/sfc.md

Closes #554 
I haven't tested on local, and I need to copy entries to `docs/ja/guide/advanced/sfc.md`.
Can I add `vitepress` to `dev dependencies` (what version have you installed globally?). 
I'm not a fan of using global dependencies...

docs: add `defaultSFCLocale` and `globalSFCScope` to sfc

---

docs/guide/advanced/optimization.md
packages/size-check-vue-i18n/rollup.config.js
packages/vue-i18n/README.md
packages/vue-i18n/src/misc.ts
rollup.config.js

Internally, it was changed from `__VUE_I18N_PROD_DEVTOOLS__` to `__VUE_PROD_DEVTOOLS__`.
This makes it unnecessary to specify `__VUE_I18N_PROD_DEVTOOLS__` in bundlers such as vite, since it works together with vue optimization.

improvement: deprecated __VUE_I18N_PROD_DEVTOOLS__ feature flag

---

examples/type-safe/global-type-definition/src/components/HelloWorld.vue
examples/type-safe/global-type-definition/vite.config.ts
examples/type-safe/type-annotation/vite.config.ts

1. Fix `not found key` warning in `examples/type-safe/global-type-definition`,   see [this implementation](https://github.com/intlify/vue-i18n-next/blob/6eaf91ae864f128676d5f6000986ee8ae31f77cf/packages/vue-i18n-core/src/i18n.ts#L599)
```ts
const scope: I18nScope = isEmptyObject(options)
? ('__i18n' in instance.type)
? 'local'
: 'global'
: !options.useScope
? 'local'
: options.useScope
```
It will set scope to `local` when `options` is not empty and `options.useScope` was not config. So in this case we should explicit use global scope.
2. Fix  `feature flag` warning in `examples/type-safe/global-type-definition` and `examples/type-safe/type-annotation` by config flags in `vite.config.ts`

Fix type-safe example warning

---

docs/guide/advanced/composition.md
docs/ja/guide/advanced/composition.md

added missing comma in code example in "Advanced > Composition API > Basic Usage" to prevent copy paste compiler errors

added missing comma in code example in Advanced > Composition API 

---

docs/guide/advanced/composition.md

In the page about the Composition API, there's an "it's" that should be spelled "its" instead. This was fixed.

Fixed a type in the Composition API documentation (it's -> its)

---

packages/message-compiler/src/tokenizer.ts
packages/message-compiler/test/fixtures/20_newsgroups_alt_atheism_51060.txt
packages/message-compiler/test/tokenizer.test.ts
packages/vue-i18n-core/src/i18n.ts

- Rewrite readText as an iterative version
- Fix warning in test

fix: Maximum call stack size

---

packages/vue-i18n/src/i18n.ts
packages/vue-i18n/test/i18n.test.ts

fix: Built-in components bugs

---

rollup.config.js

See this [comment](https://github.com/intlify/vue-i18n-next/issues/736#issuecomment-947275731) in #736

fix: remove terser option pure_getters: true, avoid wrong tree-shaking

---

packages/core-base/src/translate.ts
packages/core-base/test/translate.test.ts

fix(core-base): fallback interpolation should not break in runtime only (fix #768)

---

packages/core-base/src/errors.ts
packages/vue-i18n-core/src/errors.ts
packages/vue-i18n-core/src/warnings.ts

fix: not correct error and warning codes

---

packages/vue-i18n-core/src/i18n.ts
test-d/vue-i18n/i18n.test-d.ts

improve types declaration

---

packages/vue-i18n-core/src/mixins/next.ts

fix: avoid undefined read

---

e2e/composition.test.js
examples/legacy/composition.html
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/errors.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/mixins/next.ts
packages/vue-i18n-core/test/i18n.test.ts

feat: Support `useI18n` for Legacy API mode

---

docs/guide/advanced/optimization.md
jest.config.js
packages/global.d.ts
packages/size-check-vue-i18n/rollup.config.js
packages/vue-i18n/README.md
packages/vue-i18n/src/misc.ts
rollup.config.js

bring from: #461 #514 #583
resolve: #810

improvement: esm-bundler warning

---

packages/vue-i18n-core/src/errors.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/test/i18n.test.ts

improvement: allow custom block `useI18n` on Legacy API mode

---

docs/.vitepress/theme/Layout.vue

Fix a typo in a slot of the default theme's `<Layout/>` component.

fix: typo in the layout slot

---

packages/vue-i18n-bridge/README.md

- Add missing `import VueI18n from 'vue-i18n'` vue-i18n-bridge examples
- Change position of `castToVueI18n` to avoid type error in `Vue.use(i18n)`

docs: add missing imports and fix typescript example of vue-i18n-bridge

---

packages/vue-i18n-core/src/components/Translation.ts

We change the Slots keys to be resolved in the render function, which in Vue 3 can be resolved in the setup function, but in Vue 2.7 can only be resolved in the render function
related #1062

fix: slot resolving in render function

---

docs/guide/advanced/directive.md

The docs don't explain that the object syntax of the custom directive can accept the `plural` parameter.

Added pluralization example to custom directive page

---

docs/guide/advanced/optimization.md

Fixed the typo "const paht" to "const path"

Fix(docs): Fixing Typo in optimization.md

---

examples/ssr/vite/server.js
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/directive.ts

fix: scope execution context resolving

---

packages/vue-i18n-core/src/directive.ts

fix: conflict process global object in vDirective function

---

packages/vue-i18n-bridge/package.json
pnpm-lock.yaml

In Vue 2.7, `@vue/compostion-api` is not required. In `@vue/compostion-api` `peerDependeces`, the Vue version is defined as 2.
vue-i18n-routing works with Vue 2 / Vue 3, but will not work in a Vue 3 environment if `peerDepependeces` is left as is.

fix: change to `optionalDependencies`

---

packages/vue-i18n-core/src/legacy.ts

In VueI18nResolveLocaleMessageTranslation

fix typo in legacy API

---

docs/guide/advanced/directive.md

`$t` is function of "Vue18n" instance. It has the following pros and cons.
Incorrect : "Vue18n"
Change: "VueI18n"

Updated directive.md

---

packages/vue-i18n-core/src/components/Translation.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/symbols.ts
packages/vue-i18n-core/test/__snapshots__/composer.test.ts.snap
packages/vue-i18n-core/test/composer.test.ts

I'm not entirely sure whether the error shown is due to the typos, but nevertheless worth correcting :)
(occured when using the `<i18n-t>` component with `@nuxtjs/i18n@next`)

fix: correct typo in `TranslateVNodeSymbol`

---

docs/.vitepress/config.ts

There is a search issue on the doc site (https://vue-i18n.intlify.dev/) 
The non-English page is excluded by adding the configuration parameter of Algolia.
Issue 
https://github.com/intlify/vue-i18n-next/issues/1218

Docs: search for "useI18n" yields non-existing /ja/api/composition.html 

---

docs/guide/integrations/nuxt3.md

- I fixed the link to the prerequisites linking to a non-existing page.
- I added a link to the up-to-date v3 docs of this module since it is still in development (beta), but fully working and usable.
- fixed typos and grammar of the introduction

Fixed Links, added up-to-date link to v3 docs

---

e2e/composition.test.js
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/test/i18n.test.ts

Given the following config:
- `allowComposition: true`
- `legacy: true`
Calling `useI18n()` always results in
translations using the default language
"en-US".
Fixes: #1315

fix: global locale is not respected by useI18n

---

docs/guide/integrations/nuxt3.md

Insert a space before the link text in order for the translation tool to translate it correctly.
|before|after|
|---|---|
|<img width="515" alt="スクリーンショット 2023-02-19 23 47 29" src="https://user-images.githubusercontent.com/20086673/219955691-ea0f5e0e-6fe4-456e-bd2d-b6fe75eb8d54.png">|<img width="515" alt="スクリーンショット 2023-02-19 23 49 22" src="https://user-images.githubusercontent.com/20086673/219955699-2f1f570c-5e5c-446b-9a66-020f2e0a71d7.png">|

docs: Add space before link text

---

docs/guide/advanced/typescript.md

The deleted sentence was the same as the first one in this paragraph.

Fixed double sentence

---

docs/.ja/ecosystem/official.md
docs/ecosystem/official.md

resolves #1101
I added a section to Ecosystem page.
Sentences are based on [README of petite-vue-i18n](https://github.com/intlify/vue-i18n-next/tree/master/packages/petite-vue-i18n#petite-vue-i18n).

docs: add section about petite-vue-i18n

---

.github/CONTRIBUTING.md
package.json
packages/core-base/package.json
packages/core/package.json
packages/devtools-if/package.json
packages/message-compiler/package.json
packages/petite-vue-i18n/package.json
packages/shared/package.json
packages/vue-devtools/package.json
packages/vue-i18n-bridge/package.json
packages/vue-i18n-core/package.json
packages/vue-i18n/package.json

No related issues.
Node versions specified in the codebase and docs are inconsistent.
This PR is to unify Node versions to 16 for 2 reasons:
- only Node 16 is tested in CI (i.e. `.github/workflows/ci.yml`)
- the associated commit to `.github/workflows/ci.yml` is newer than other places (e.g. commit to `package.json`)
⚠️ This is my very first PR for this repository, so I might be missing something.

fix: drop node v14

---

packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/utils.ts

ref: https://github.com/nuxt-modules/i18n/issues/2112

fix: avoid transform to `globalThis` with bundler

---

packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/test/components/Translation.test.ts
packages/vue-i18n-core/test/issues.test.ts

fix: Resolve the message in components which was rendered with slots, for about `<i18n-t>`, `<i18n-n>` and `<i18n-d>`

---

packages/vue-i18n-core/src/plugin/next.ts
packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
packages/vue-i18n-core/test/issues.test.ts
packages/vue-i18n-core/test/plugin.test.ts

fix: reslove with caml-case for components

---

docs/.ja/api/component.md

- Typo in documentation when referring to translation component.
- Removed the translation component referred to i18n and updated it to i18n-t

Fix #1475: Typo in documentation when referring to translation component

---

packages/vue-i18n-core/src/i18n.ts

fix: cleanup global injection resources

---

docs/.ja/api/legacy.md
packages/petite-vue-i18n/src/index.ts
packages/petite-vue-i18n/src/runtime.ts
packages/vue-i18n-bridge/src/index.ts
packages/vue-i18n-bridge/src/runtime.ts
packages/vue-i18n-core/src/index.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/mixins/next.ts
packages/vue-i18n-core/test/i18n.test.ts
packages/vue-i18n-core/test/mixin.test.ts
packages/vue-i18n/src/index.ts
packages/vue-i18n/src/runtime.ts

`componentInstanceCreatedListener` is an I/F for nuxt i18n. nuxt i18n v8 no longer needs this I/F. And this I/F is undocument. So remove it.

fix: drop componentInstanceCreatedListener

---

docs/guide/advanced/optimization.md

Avoid reader using wrong plugin when compiled and minified for production on vite 4.

docs: add vite-plugin-vue-i18n support vite version to warning notice

---

packages/core-base/src/translate.ts
packages/core-base/test/translate.test.ts

I noticed this issue when I've created [this PR](https://github.com/intlify/bundle-tools/pull/287)

fix(core-base): `isMessageAST` more strictly

---

examples/frameworks/nuxt3/package.json

This pull request updates all devDependencies of Nuxt 3 Minimal Starter Example to their latest versions, enhancing stability, security, and performance:
- @intlify/unplugin-vue-i18n to "^1.0.1"
- nuxt to "^3.7.1"
- vue-i18n to "^9.3.0"

Update All devDependencies Nuxt 3 Minimal Starter Example to Latest Versions

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test.ts
pnpm-lock.yaml

This pull request introduces a small fix to i18n-next that addresses an issue where
`i18n.te(null)` or `i18n.te(undefined)` will not provide false

Handle falsy values in i18n.te()

---

docs/guide/installation.md
packages/core/README.md
packages/vue-i18n/README.md
rollup.config.mjs

This PR  is for #1569.
We need to support `@intlify/unplugin-vue-i18n` to fix it fully.

fix: support runtime module for node.js

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test.ts
packages/vue-i18n-core/test/issues.test.ts

fix: strictly key exsisting with `te`

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/issues.test.ts

fix: more `te` logic strictly

---

packages/core-base/src/runtime.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test.ts

fix: `te` fallback to root

---

packages/core-base/src/resolver.ts
packages/core-base/test/resolver.test.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/issues.test.ts

fix: return null for fucntion

---

packages/vue-i18n-bridge/src/vue.d.ts
packages/vue-i18n/src/vue.d.ts

* This change seems to resolve https://github.com/nuxt-modules/i18n/issues/2483
Not sure why this change fixes the type inference issue 😅 Also curious why this issue did not show up sooner..

fix: Nuxt I18n type inference

---

test-dts/vue-i18n/components.test-d.tsx

In Vue 3.4, implicit global JSX type registration will be removed. Explicitly importing `vue/jsx` preserves the old behavior.

Register vue jsx types in tsx test

---

packages/petite-vue-i18n/src/vue.d.ts
packages/vue-i18n-bridge/src/vue.d.ts
packages/vue-i18n/src/vue.d.ts
scripts/build.sh
scripts/build.ts

This PR is created based on [a conversation on Twitter](https://x.com/NozomuIkuta/status/1741107199001383376?s=20).
With this PR, we do no longer need to manage from which line of `<target>/src/vue.d.ts` should be appended to `<target>/dist/<target>.d.ts`. All the content below the marker string will be automatically appended.
Diffs in `vue.d.ts` files are mostly generated by Prettier.
All I did to those was to add "// --- THE CONTENT BELOW THIS LINE WILL BE APPENDED TO DTS FILE IN DIST DIRECTORY --- //" as the marker string.
---
This PR change build process, so please review carefully.

chore: improve Vue type definition appending

---

packages/shared/src/messages.ts
packages/vue-i18n-core/src/composer.ts

Not sure if there are downsides to using `shallowRef` instead of `ref` only on the server-side. As I understand it there's no reactivity on the server-side, so this shouldn't change much, besides not setting up reactivity tracking for nested keys?
In my testing this fixes the messages from leaking when using computed translations after an async function in Nuxt. I can only guess that the reason for it is that the computed translation is referencing a key inside the object preventing it from being disposed. I don't think this fixes the root cause of the leak in `@nuxtjs/i18n`, but maybe lowers memory usage overall.
I have also changed the `deepCopy` function to use iteration instead of recursion, which should lower memory usage as well.
I have tested this with …

fix: lower memory usage

---

docs/ecosystem/official.md

The current one gives a 404 from github pages.

chore(docs): change eslint plugin's URL to the right github repo

---

docs/.ja/ecosystem/tools.md
docs/guide/integrations/nuxt3.md

I noticed the docs still refer to Nuxt I18n as not being ready yet for Nuxt 3, hopefully this prevents some confusion about the module status.

docs: update description of Nuxt I18n and its status

---

packages/petite-vue-i18n/src/vue.d.ts
packages/vue-i18n-bridge/src/vue.d.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/issues.test.ts
packages/vue-i18n/src/vue.d.ts

fix: Support for `te` behavior compatibility before v9.6

---

packages/message-compiler/src/generator.ts

Resolves #1760 (tested locally using the provided reproduction)
Not sure if this would cause other issues, I haven't tested this in more projects.
After spending some time trying to figure out _why_ the triple slash directive is being added, I gave up. The actual problem in #1760 is the path inside the directive, so after adding one manually I found out that this removes the directive from the build (huh?).

fix: manually add triple slash directive to `message-compiler`

---

docs/guide/installation.md

Just a typo on the installation.md 👀

fix(installation.md): typo on es modules

---

packages/vue-i18n-core/src/components/DatetimeFormat.ts
packages/vue-i18n-core/src/components/NumberFormat.ts

Related downstream https://github.com/nuxt-modules/i18n/issues/2895
Resolves https://github.com/intlify/vue-i18n-next/issues/1331
It looks like the `scope` prop is not being used by the `<i18n-n>` and `<i18n-d>` components, this should make this prop work the same way as it does for the `<i18n-t>` component while still using `'parent'` as default value.
I tested this locally using the Nuxt i18n playground (if formatting worked and no warning logged), let me know if tests need to be added!

fix: number and date format components not using `scope` prop

---

packages/message-compiler/src/tokenizer.ts
packages/message-compiler/test/tokenizer/named.test.ts
packages/vue-i18n-core/test/issues.test.ts
spec/syntax.ebnf

fix: compile error for key with included hyphen in named interpolation

---

packages/message-compiler/src/tokenizer.ts
packages/message-compiler/test/__snapshots__/parser.test.ts.snap
packages/message-compiler/test/__snapshots__/tokenizer.test.ts.snap
packages/message-compiler/test/tokenizer.test.ts
packages/vue-i18n-core/test/issues.test.ts
spec/syntax.ebnf

fix(message-compiler): cannot resolve none-identifier characters at linked key

---

packages/vue-i18n-core/src/i18n.ts
test-dts/vue-i18n/i18n.test-d.ts

fix(types): allow spyOn of "useI18n()"

---

docs/.vitepress/config.mts

Noticed there's no favicon configured, this only uses the existing `.png` icon file as there's no `.ico` variant of this, this should work fine but I could generate an `.ico` file if preferred.
This should make it a bit easier to find Vue I18n with lots of tabs opened 😅

docs: add favicon

---

docs/guide/advanced/format.md
docs/guide/advanced/typescript.md
docs/guide/advanced/wc.md
docs/guide/essentials/started.md
docs/guide/integrations/nuxt3.md

Fixes some small typos in the docs

docs: fix typos

---

docs/.ja/guide/advanced/composition.md
docs/guide/advanced/composition.md
docs/guide/migration/breaking.md
packages/petite-vue-i18n/src/index.ts
packages/petite-vue-i18n/src/runtime.ts
packages/vue-i18n-core/src/index.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/legacy.test.ts
packages/vue-i18n/src/index.ts
packages/vue-i18n/src/runtime.ts

`formatter` options was deprecated in v9.

breaking: drop fully `formatter` option codes on Legacy API

---

docs/.ja/guide/advanced/composition.md
docs/guide/advanced/composition.md
docs/guide/migration/breaking.md
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/warnings.ts

`preserveDirectiveContent` options was deprecated in v9.

breaking: drop fully `preserveDirectiveContent` option codes on Legacy API

---

docs/guide/migration/breaking.md
packages/vue-i18n-core/src/directive.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/diretive.test.ts

`preserve` modifier was deprecated in v9.

breaking: drop fully `preserve` modifier codes on `v-t` directive

---

docs/.ja/guide/advanced/composition.md
docs/guide/advanced/composition.md
docs/guide/migration/breaking.md
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/legacy.test.ts

`getChoiceIndex` was deprecated in v9.

breaking: drop fully `getChoiceIndex` on Legacy API

---

.github/workflows/ci.yml
docs/.vitepress/config.mts
docs/api/injection.md
docs/guide/migration/breaking.md
docs/guide/migration/breaking10.md
docs/guide/migration/features.md
examples/legacy/components/translation.html
packages/petite-vue-i18n/src/vue.d.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/test/i18n.test.ts
packages/vue-i18n-core/test/legacy.test.ts
packages/vue-i18n/src/vue.d.ts

In Vue I18n v9, it has a different interface from the Composition API mode and Legacy API mode of the `$t` overloaded signature.
Especially, `$t` signature in Legacy API mode has fewer overloaded signatures than in Composition API mode, as shown below:
| `$t` overloaded signatures                                                       | Legacy API v9 | Legacy API v10 | Composition API v9 & v10 |
| -------------------------------------------------------------------------------- | ------------- | -------------- | ------------------------ |
| `$t(key: Path): TranslateResult;`                                                | ✅            | ✅             | ✅                       |
| `$t(key: Path, locale: Locale): TranslateResult;`                                | ✅            | - …

feat!: change `$t` overloaded signature for Legacy API mode

---

docs/api/injection.md
docs/guide/migration/breaking10.md
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/i18n.test.ts
packages/vue-i18n-core/test/legacy.test.ts
packages/vue-i18n-core/test/mixin.test.ts
packages/vue-i18n-core/test/warnings.test.ts

The following APIs are deprecated in v10:
- `tc(key: Key | ResourceKeys): TranslateResult;`
- `tc(key: Key | ResourceKeys, locale: Locales | Locale): TranslateResult;`
- `tc(key: Key | ResourceKeys, list: unknown[]): TranslateResult;`
- `tc(key: Key | ResourceKeys, named: Record<string, unknown>): TranslateResult;`
- `tc(key: Key | ResourceKeys, choice: number): TranslateResult;`
- `tc(key: Key | ResourceKeys, choice: number, locale: Locales | Locale): TranslateResult;`
- `tc(key: Key | ResourceKeys, choice: number, list: unknown[]): TranslateResult;`
- `tc(key: Key | ResourceKeys, choice: number, named: Record<string, unknown>): TranslateResult;`
- `$tc(key: Key): TranslateResult;`
- `$tc(key: Key, locale: Locale): TranslateResult;`
- `$tc(key: Key, list: unknown[]): TranslateResult;`
- …

feat!: deprecate `tc` and `$tc` for Legacy API mode

---

packages/vue-i18n-core/src/plugin.ts
packages/vue-i18n-core/src/plugin/next.ts
packages/vue-i18n-core/src/plugin/types.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/helper.ts
packages/vue-i18n-core/test/plugin.test.ts
packages/vue-i18n-core/test/warnings.test.ts

`useI18nComponentName` option was deprecated in v9.

breaking: drop translation component `<i18n>` v8.x compatibility

---

docs/guide/essentials/started.md

Just a small fix in the _Getting Started_ section of the docs where it said "Vue Router" but I think it meant "Vue I18n" 🙂

docs: fix typo on vue i18n name

---

packages/core-base/src/errors.ts
packages/core-base/src/index.ts
packages/core-base/src/warnings.ts
packages/core-base/test/errors.test.ts
packages/core-base/test/warnings.test.ts
packages/message-compiler/package.json
packages/message-compiler/src/errors.ts
packages/shared/src/utils.ts
packages/shared/test/utils.test.ts
packages/vue-i18n-core/src/errors.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/warnings.test.ts

We can reduce around 1KB
https://github.com/intlify/vite-vue-i18n-starter/tree/vite5

perf: more bundle size optimization

---

packages/core-base/src/types/utils.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n/src/vue.d.ts

This PR addresses 2 problems with Typescript types:
- #1215: By removing the type `Path` from the `key: Key | ResourceKeys | Path`, we get type inference to work again and suggest valid translations when using globally injected `$t`. Since the type `Key extends string` already extends from `string`, it shouldn't cause any regression. For the type inference to work when using `$t`, you have to extend the module types:
```ts
import en from '@src/assets/locales/en.json';
type Messages = typeof en;
declare module 'vue-i18n' {
export interface DefineLocaleMessage extends Messages {}
}
```
- When fixing the first issue, I found that nested keys are treated as translations by themselves. For example:
```json
{
"this": {
"is": {
"a": {
"nested": {
"key": "This is a nested key"
}
}
}
}
}
```
When …

fix(types): `$t` types

---

package.json
packages/vue-i18n-core/test/__snapshots__/composer.test.ts.snap
pnpm-lock.yaml

This is the same as https://github.com/intlify/vue-i18n/pull/1895 with an additional commit to update the snapshot as suggested by https://github.com/intlify/vue-i18n/pull/1895#issuecomment-2236005556.

chore(deps): update dependency vue to v3.4.32

---

packages/core-base/src/runtime.ts

The module augmentation should use `@intlify/core-base`, not `@intlify/core`, as described in https://github.com/nuxt-modules/i18n/pull/3034.

chore: fix module augmentation example comment

---

.github/workflows/ci.yml
e2e/helper.ts
package.json
pnpm-lock.yaml
scripts/playwright.ts
scripts/vitest.setup.ts
shim.d.ts

Basically the same as https://github.com/nuxt-modules/i18n/pull/3040, removes caching as per the recommendations of `playwright`.

ci: update test dependencies and remove playwright caching

---

.github/workflows/ci.yml

Using `contains()` for `'chore'` and `'docs'` will prevent nightly release job from running if these words are used anywhere in the commit message, this is (especially) problematic for squashed PRs as they contain a list of all commits.
Checking with `startsWith()` instead will probably have to intended behavior.

fix: nightly release condition

---

packages/petite-vue-i18n/src/vue.d.ts
packages/vue-i18n-bridge/src/vue.d.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n/src/vue.d.ts

As discussed in https://github.com/intlify/vue-i18n/pull/1888 we will need this to prevent breaking types!

fix: vue-i18n type definition for vue package

---

docs/guide/essentials/scope.md

The earlier text seemed a little difficult to understand. Made some changes to make it comprehensible.

Improved the global and local Scope descriptions

---

package.json
packages/core-base/src/context.ts
packages/core-base/src/resolver.ts
packages/vue-i18n-core/src/i18n.ts
pnpm-lock.yaml
rollup.config.mjs

I was checking to see if updating Rollup would improve build speed 😅 I noticed a bunch of warnings while building due to the PURE comments usage, this is new in Rollup 4 https://rollupjs.org/migration/#general-changes:~:text=Last%2C%20you%20may,can%20help%20you, so likely these comments were not actually being used. 
These warnings can be seen in the build step of https://github.com/intlify/vue-i18n/pull/1578, I've listed some of them below:
Variable assignments
* https://github.com/intlify/vue-i18n/actions/runs/10795109412/job/29940976048?pr=1578#step:6:60
* https://github.com/intlify/vue-i18n/actions/runs/10795109412/job/29940976048?pr=1578#step:6:103
* https://github.com/intlify/vue-i18n/actions/runs/10795109412/job/29940976048?pr=1578#step:6:118
Function calls
* …

chore(deps): update `rollup`

---

packages/shared/src/messages.ts
packages/shared/test/messages.test.ts

>[!IMPORTANT]
>This has not been thoroughly tested but should demonstrate the issue with `deepCopy`
Currently during `deepCopy` if a key is unset, it will be assigned to the value of the `src[key]`, this is an issue for objects as they will be assigned by reference, meaning following calls to `deepCopy` will assign properties on these objects.
So far a simple solution seems to be to set the property value to an empty object/array, this ensures both `src[key]` and `des[key]` are objects meaning `deepCopy` will merge these as such instead of direct assignment.
I've had this saved in a git stash for some time so it has been a while since debugging this issue, I'm opening this PR so I won't forget about it again 😅
https://github.com/nuxt-modules/i18n/issues/3089 …

fix: messages `deepCopy` mutates `src` arguments

---

docs/guide/advanced/lite.md
packages/petite-vue-i18n/src/index.ts
packages/petite-vue-i18n/src/runtime.ts

fix(petite-vue-i18n): cannot register correctly message resolver and locale fallbacker

---

docs/guide/advanced/lite.md

docs: add unplugin-vue-i18n setting for petite-vue-i18n

---

README.md

Additionally, fixed wrong link of `vue-i18n-bridge` package, and added trailing pipes for table.

Add petite-vue-i18n package to README

---

scripts/release-edge.sh
scripts/release.sh

It looks like the previous releases for v9 have been tagged with `latest`, so users installing these packages are not getting v10.
Not sure if you want v9 releases to be tagged as `legacy9` and `next9`, feel free to change it. Also not sure if these are the only spots where the tags are being set 🤔
Perhaps the v10 version tags can be fixed by rerunning the release action.

fix: tag v9 releases with `legacy9` and `next9`

---

packages/core-base/src/format.ts
packages/core-base/test/format.test.ts
packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
packages/message-compiler/test/__snapshots__/optimizer.test.ts.snap
packages/message-compiler/test/compiler.test.ts
packages/message-compiler/test/optimizer.test.ts
packages/message-compiler/test/parser/__snapshots__/literal.test.ts.snap
packages/message-compiler/test/parser/literal.test.ts
packages/message-compiler/test/tokenizer/literal.test.ts
packages/vue-i18n-core/test/issues.test.ts

fix: cannot resolve empty string on plural

---

docs/guide/advanced/composition.md

- removed repeated sentence
- corrected spelling

Fix: Composition.md

---

docs/guide/advanced/composition.md

Updated the example output in the documentation to reflect the correct HTML structure. Changed `<p>` tags to `<h1>` tags to align with the intended rendered output:
Previous output: `<p>こんにちは、世界</p>`
Corrected output: `<h1>こんにちは、世界</h1>`

fix(docs): correct output in composition api example

---

packages/vue-i18n/src/vue.d.ts

It looks like the `$tm` function on `ComponentCustomProperties` does not use the `DefineLocaleMessage` type for the key parameter. This is a simple copy paste of the type parameters used for `$t`, which I think should be the same for the keys.

fix: `tm` function should accept `DefineLocaleMessage` key type

---

e2e/fallback/basic.spec.ts
e2e/fallback/format.spec.ts
e2e/fallback/option.spec.ts
e2e/fallback/suppress.spec.ts
e2e/missing/handler.spec.ts
e2e/missing/option.spec.ts
e2e/missing/suppress.spec.ts
package.json
packages/size-check-petite-vue-i18n/src/main.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/i18n.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/src/warnings.ts
packages/vue-i18n-core/test/directive.test.ts
packages/vue-i18n-core/test/ssr.test.ts
pnpm-lock.yaml

The Legacy API mode was the API mode compatible with vue-i18n v8 for Vue 2. When vue-i18n v9 was released, the Legacy API was provided to smooth the migration from v8 to v9.
Legacy API mode will be deprecated in vue-i18n v11, as previous vue-i18n releases have already provided the following to support migration to Composition API mode
- Migration from Legacy API mode to Composition API mode: https://vue-i18n.intlify.dev/guide/migration/vue3.html
- Composition API usage: https://vue-i18n.intlify.dev/guide/advanced/composition.html
For compatibility, Legacy API mode still works in vue-i18n v11, but will be removed entirely in vue-i18n v12, so Legacy API mode will not work after that version.
- more simple: we will no longer need to worry about the Legacy API mode and Composition API mode. …

feat!: deprecate Legacy API mode

---

docs/guide/essentials/pluralization.md

docs: fix wrong plural example

---

docs/guide/essentials/pluralization.md

While browsing documents, I found the word `gloal` that seems to have a spelling error. It appears to express the meaning of `global`, so I made the correction in this PR.
- File: docs/guide/essentials/pluralization.md
- Line: 37
**Before:**
```
- injected gloal `$t`
```
**After:**
```
- injected global `$t`
```

docx(pluralization.md): Correct spelling from 'gloal' to 'global'

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/legacy.ts
packages/vue-i18n-core/test/composer.test.ts
packages/vue-i18n-core/test/legacy.test.ts

resolves #1893 
so, I had the same problem and as a solution I implemented the idea suggested by the man who created the issue using `computed` in `availableLocales` at `composer.ts`
also I wrote some tests and change some things in `legacy.ts` to accommodate this of course
now its works great :)

feat: reactive `availableLocales` using computed property

---

.github/workflows/size-report.yml
packages/core-base/test/compilation.test.ts
packages/message-compiler/src/compiler.ts
packages/message-compiler/src/mangler.ts
packages/message-compiler/src/options.ts
packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
packages/message-compiler/test/__snapshots__/mangler.test.ts.snap
packages/message-compiler/test/compiler.test.ts
packages/message-compiler/test/mangler.test.ts

In the context of javascript code minification, especially in terser, it's used `mangle` word, so we will according to it.

feat!: change to `mangle` option name from `minify` option name

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test.ts

reproduction: https://codesandbox.io/p/devbox/vue-i18n-9-template-forked-ffq44z
This PR adjusts the order of operations in the locale setter to rectify the issue where, during locale updates, a synchronous watcher may trigger after modifying the _locale.value (as seen in [this file](https://github.com/intlify/vue-i18n/blob/897829bff49fe4694cc9fc0c571d2d42652e4b9f/packages/vue-i18n-core/src/composer.ts#L2113), but before updating the _context. This sequence led to errors because the translation mechanism relies exclusively on _context, not _locale.

Fix: Synchronous Watcher Issue Caused by Locale Setting Order

---

.github/workflows/ci.yml
.github/workflows/nightly-release.yml
.github/workflows/release.yml
package.json

close https://github.com/intlify/vue-i18n/issues/2099
hi
I saw a post on the chibivue server and came to help.
I confirmed that build and test are working.
Unclear points:
How to run tests in workflows
Do I also need to modify package.json under `packages`?

drop node v18

---

packages/vue-i18n-core/test/helper.ts

👋 Here is a type fix to make https://github.com/vuejs/core/pull/12935 pass ecosystem CI.

fix: update MountOptions.components type

---

packages/core-base/src/ast.ts
packages/core-base/src/compilation.ts
packages/core-base/src/format.ts
packages/core-base/src/index.ts
packages/core-base/src/resolver.ts
packages/core-base/src/translate.ts
packages/core-base/test/compilation.test.ts
packages/core-base/test/fixtures/ast.ts
packages/core-base/test/resolver.test.ts
packages/core-base/test/translate.test.ts
packages/vue-i18n-core/src/utils.ts
packages/vue-i18n-core/test/fixtures/ast.ts
packages/vue-i18n-core/test/issues.test.ts
packages/vue-i18n-core/test/utils.test.ts

fix: cannot resolve the ast messages which has json path

---

packages/vue-i18n-core/src/types.ts

I'm running into an issue while implementing https://github.com/nuxt-modules/i18n/pull/3341
In the build it looks like the `GeneratedTypeConfig` interface gets renamed to `GeneratedTypeConfig_2` and is no longer exported, which means we can't augment it.
This is what the type looks like in the build currently:
```ts
declare type GeneratedInstanceType = GeneratedTypeConfig_2 extends Record<'legacy', infer Legacy> ? Legacy : never;
export { GeneratedTypeConfig }
```

fix: duplicate generated type config naming

---

e2e/bridge/basic.spec.ts
e2e/bridge/component.spec.ts
e2e/bridge/components/datetime-format.spec.ts
e2e/bridge/components/number-format.spec.ts
e2e/bridge/components/translation.spec.ts
e2e/bridge/plural.spec.ts
e2e/bridge/scope/global.spec.ts
e2e/bridge/scope/inherit-locale.spec.ts
e2e/bridge/scope/local.spec.ts
packages/core-base/src/ast.ts
packages/core-base/src/compilation.ts
packages/core-base/src/format.ts
packages/core-base/src/index.ts
packages/core-base/src/resolver.ts
packages/core-base/src/translate.ts
packages/core-base/test/compilation.test.ts
packages/core-base/test/fixtures/ast.ts
packages/core-base/test/resolver.test.ts
packages/core-base/test/translate.test.ts
packages/vue-i18n-core/src/utils.ts
packages/vue-i18n-core/test/fixtures/ast.ts
packages/vue-i18n-core/test/issues.test.ts
packages/vue-i18n-core/test/utils.test.ts

fix: cannot resolve the ast messages which has json path for v9

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test-d.ts
packages/vue-i18n-core/test/composer.test.ts
packages/vue-i18n/src/vue.d.ts

- Added support for part in $n.
- Added test cases
- might resolve https://github.com/intlify/vue-i18n/issues/1165

Part options support for $n

---

packages/petite-vue-i18n/src/vue.d.ts
packages/vue-i18n/src/vue.d.ts

related #2110
In v12, the legacy style API will be dropped. As a result, the API signatures `$t`, `$n`, and `$d` injected into components prefixed with `$` no longer need to consider the legacy style. Only the composition style applies. Note that these APIs will continue to work only in the global scope.

breaking: update component injection APIs for drop legacy

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test-d.ts
packages/vue-i18n-core/test/composer.test.ts
packages/vue-i18n/src/vue.d.ts

Back ported part option functionality for $n().
Would close https://github.com/intlify/vue-i18n/issues/2172

Part options support $n - v11

---

packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/test/composer.test-d.ts
packages/vue-i18n-core/test/composer.test.ts
packages/vue-i18n/src/vue.d.ts

Backported part option functionality for $d().
Would close https://github.com/intlify/vue-i18n/issues/2171

feat: Part options support $d

---

packages/vue-i18n-core/src/components/Translation.ts
packages/vue-i18n-core/test/components/Translation.test.ts
pnpm-lock.yaml

resolve #2189
This PR is back-port of #2167

fix: support vue core internal slot key changing

---

packages/core-base/src/translate.ts
packages/core-base/test/translate.test.ts
packages/shared/src/utils.ts
packages/shared/test/utils.test.ts
packages/vue-i18n-core/src/composer.ts
packages/vue-i18n-core/src/legacy.ts

This PR will be fixed for v9
https://github.com/intlify/vue-i18n/security/advisories/GHSA-x8qp-wqqm-57ph

fix: DOM-based XSS via tag attributes for escape parameter

---

docs/api/composition.md
docs/api/general.md

Found via `codespell docs/ -L te,manger,custome`

docs: fix typos in docs
